TLA+ spec of CCV
cosmos/ics pull request #911
Opened 2023-01-16 15:21 UTC by Kukovec

This PR ports and updates the previously created CCV TLA+ spec from https://github.com/cosmos/interchain-security/tree/jk/ISaudit.
It includes additional modeling of provider-side timeout.

2023-04-03 09:38 UTC, p-offtermatt reviewed
Looks good, mostly just nitpicks.
My only bigger issue is that the document the invariants were taken from
was deprecated. I think those should be properties outlined in the spec instead.

2023-04-04 10:23 UTC, mpoke commented on spec/app/ics-028-cross-chain-validation/tla/CCV.tla
> +RcvPacket ==
RcvVPCPacket and make it consistent throughout the entire model.

2023-04-04 11:31 UTC, p-offtermatt commented
@mpoke applied the review suggestions.
Decided to leave the invariants from the old QA document (but the link is fixed),
since it is unclear how we will proceed with it.

2023-04-11 08:07 UTC, p-offtermatt approved these changes

2023-04-25 14:00 UTC, mpoke requested changes
@p-offtermatt here are some comments after a first review. I still have to review the properties and invariants.

2024-03-28 16:19 UTC, crodriguezvega commented
As discussed we will close this PR and add a link to the existing Quint spec.

2024-03-28 16:19 UTC, closed without merging